/***********************************************************  
USUARIO
***********************************************************/
CREATE TABLE USUARIO
(
    COD_USUARIO		  			INT NOT NULL 	AUTO_INCREMENT,
	NOME     					VARCHAR(200) 	NOT NULL,
	CPF_CNPJ					VARCHAR(30) 	NULL,
    LOGIN     					VARCHAR(20) 	NOT NULL,
    SENHA    		        	VARCHAR(100) 	NULL,
	EMAIL     					VARCHAR(100) 	NOT NULL,
    DTH_CRIACAO              	DATETIME        DEFAULT CURRENT_TIMESTAMP, 
	DTH_CANCELAMENTO          	DATETIME        NULL,    
    ENDERECO					VARCHAR(200) 	NOT NULL,
	NUMERO 						NUMERIC 		DEFAULT 0,
    CIDADE						VARCHAR(100) 	NOT NULL,
    UF							CHAR(2) 		NOT NULL,
    BAIRRO						VARCHAR(100) 	NOT NULL,
	PAIS						VARCHAR(100) 	NOT NULL,
    CEP							VARCHAR(10) 	NULL,
    COMPLEMENTO					VARCHAR(100) 	NULL,
    TELEFONE					VARCHAR(15) 	NULL,
    CELULAR						VARCHAR(15) 	NULL,
	SEXO     					CHAR(1) 	   	NOT NULL,
	FLAG_ADM 					CHAR(1) 	   	NOT NULL,
	FOTO 						LONGTEXT 		NULL,   
	STATUS 					    CHAR(1) 	   	NOT NULL,
    PRIMARY KEY (COD_USUARIO)
);

ALTER TABLE USUARIO AUTO_INCREMENT = 1000;

/***********************************************************  
ACESSO
***********************************************************/
CREATE TABLE ACESSO
(
    COD_ACESSO	  				INT NOT NULL 	AUTO_INCREMENT,
	COD_USUARIO		  			INT 			DEFAULT NULL,  
	TIPO_USUARIO				CHAR(1)         NULL,
    IP    		        		VARCHAR(100) 	NULL,
	BROWSER	        			VARCHAR(100) 	NULL,
	PLATAFORMA        			VARCHAR(100) 	NULL,
	RESOLUCAO   				VARCHAR(100) 	NULL,
	DTH_ACESSO   				DATETIME        DEFAULT CURRENT_TIMESTAMP,
    DIA							INT				DEFAULT 0,
	MES							INT				DEFAULT 0,
	ANO							INT				DEFAULT 0,
    HORA						VARCHAR(5) 		NULL,
	URL_ACESSO					VARCHAR(100) 	NULL,
    DISPOSITIVO					VARCHAR(100) 	NULL,
    DOMINIO						VARCHAR(100) 	NULL,
	SUPORTA_ACTIVEX             CHAR(1)			NULL,
	SUPORTA_COOKIES             CHAR(1)         NULL,
    SUPORTA_JAVA_APPLET			CHAR(1)         NULL,
    COORD_LATITUDE				VARCHAR(50)     NULL,
	COORD_LONGITUDE				VARCHAR(50)     NULL,
	CIDADE						VARCHAR(100)    NULL,
    PRIMARY KEY (COD_ACESSO)
);

ALTER TABLE ACESSO AUTO_INCREMENT = 0;

/***********************************************************  
TIPO_CONTATO
***********************************************************/
CREATE TABLE TIPO_CONTATO
(
    COD_TIPO_CONTATO  				INT NOT NULL 	AUTO_INCREMENT,
	NOME    		    			VARCHAR(100) 	NOT NULL,
	DESCRICAO    		        	VARCHAR(200) 	NULL,
	STATUS							CHAR(1)         NOT NULL,
    PRIMARY KEY (COD_TIPO_CONTATO)
);

ALTER TABLE TIPO_CONTATO AUTO_INCREMENT = 1000;

/***********************************************************  
CONTATO
***********************************************************/
CREATE TABLE CONTATO
(
    COD_CONTATO		  			INT NOT NULL 	AUTO_INCREMENT,
	COD_TIPO_CONTATO  			INT 			DEFAULT NULL,  
	NOME    		    		VARCHAR(100) 	NOT NULL,
    EMAIL    		    		VARCHAR(100) 	NOT NULL,
	DESCRICAO    		        TEXT 			NULL,
	DTH_CONTATO   				DATETIME        DEFAULT CURRENT_TIMESTAMP,  
	DTH_LEITURA   				DATETIME        DEFAULT NULL, 
	STATUS						CHAR(1)         NOT NULL,
    PRIMARY KEY (COD_CONTATO)
);

ALTER TABLE CONTATO AUTO_INCREMENT = 1000;

/***********************************************************  
MENU
***********************************************************/
CREATE TABLE MENU
(
    COD_MENU		  			INT NOT NULL 	AUTO_INCREMENT,
	COD_MENU_PAI	  			INT 			DEFAULT 0,
	NOME    		    		VARCHAR(100) 	NOT NULL,
	CONTROLLER					VARCHAR(100) 	NULL,
	ACTION						VARCHAR(100) 	NULL,
	DESCRICAO    		        TEXT 			NULL,
	DTH_CADASTRO   				DATETIME        DEFAULT CURRENT_TIMESTAMP,  
	ICONE						VARCHAR(100) 	NULL,
	STATUS						CHAR(1)         NOT NULL,
    PRIMARY KEY (COD_MENU)
);

ALTER TABLE MENU AUTO_INCREMENT = 1000;

-- MENU PADRAO
INSERT INTO MENU (COD_MENU, COD_MENU_PAI, NOME, CONTROLLER, ACTION, DESCRICAO, DTH_CADASTRO, ICONE, STATUS) VALUES (1000, 0, 'Administração', NULL, NULL, NULL, NULL, 'fa-cube', 'A');
INSERT INTO MENU (COD_MENU, COD_MENU_PAI, NOME, CONTROLLER, ACTION, DESCRICAO, DTH_CADASTRO, ICONE, STATUS) VALUES (1001, 1000, 'Usuarios', '/Usuario', '/Index', NULL, NULL, 'fa-stack-overflow', 'A');
INSERT INTO MENU (COD_MENU, COD_MENU_PAI, NOME, CONTROLLER, ACTION, DESCRICAO, DTH_CADASTRO, ICONE, STATUS) VALUES (1002, 1000, 'Menus', '/Menu', '/Index', NULL, '2015-09-15T01:51:39.000000', 'fa-cube', 'A');
INSERT INTO MENU (COD_MENU, COD_MENU_PAI, NOME, CONTROLLER, ACTION, DESCRICAO, DTH_CADASTRO, ICONE, STATUS) VALUES (1003, 1000, 'Históricos', '/Historico', '/Index', NULL, '2015-09-15T01:51:39.000000', 'fa-pencil', 'A');
INSERT INTO MENU (COD_MENU, COD_MENU_PAI, NOME, CONTROLLER, ACTION, DESCRICAO, DTH_CADASTRO, ICONE, STATUS) VALUES (1004, 1000, 'Bugs', '/Bugs', '/Index', NULL, '2015-09-15T01:51:39.000000', 'fa-bug', 'A');
COMMIT;

-- INSERT INTO MENU (COD_MENU, COD_MENU_PAI, NOME, CONTROLLER, ACTION, DESCRICAO, DTH_CADASTRO, ICONE, STATUS) VALUES (1000, 0, 'Administração', NULL, NULL, NULL, NULL, 'fa-cube', 'A');
-- INSERT INTO MENU (COD_MENU, COD_MENU_PAI, NOME, CONTROLLER, ACTION, DESCRICAO, DTH_CADASTRO, ICONE, STATUS) VALUES (1001, 1000, 'Usuarios', '/Usuario', '/Index', NULL, NULL, 'fa-stack-overflow', 'A');
-- INSERT INTO MENU (COD_MENU, COD_MENU_PAI, NOME, CONTROLLER, ACTION, DESCRICAO, DTH_CADASTRO, ICONE, STATUS) VALUES (1002, 1000, 'Menus', '/Menu', '/Index', NULL, '2015-09-15T01:51:39.000000', 'fa-cube', 'A');
-- INSERT INTO MENU (COD_MENU, COD_MENU_PAI, NOME, CONTROLLER, ACTION, DESCRICAO, DTH_CADASTRO, ICONE, STATUS) VALUES (1003, 1000, 'Históricos', '/Historico', '/Index', NULL, '2015-09-15T01:51:39.000000', 'fa-pencil', 'A');
-- INSERT INTO MENU (COD_MENU, COD_MENU_PAI, NOME, CONTROLLER, ACTION, DESCRICAO, DTH_CADASTRO, ICONE, STATUS) VALUES (1004, 1000, 'Bugs', '/Bugs', '/Index', NULL, '2015-09-15T01:51:39.000000', 'fa-bug', 'A');
-- INSERT INTO MENU (COD_MENU, COD_MENU_PAI, NOME, CONTROLLER, ACTION, DESCRICAO, DTH_CADASTRO, ICONE, STATUS) VALUES (1005, 0, 'Financeiro', NULL, NULL, NULL, NULL, 'fa-university', 'A');
-- INSERT INTO MENU (COD_MENU, COD_MENU_PAI, NOME, CONTROLLER, ACTION, DESCRICAO, DTH_CADASTRO, ICONE, STATUS) VALUES (1006, 1005, 'Boletos Emitidos', '/Financeiro', '/Boleto', NULL, '2015-09-15T01:51:39.000000', 'fa-file-text-o', 'A');
-- INSERT INTO MENU (COD_MENU, COD_MENU_PAI, NOME, CONTROLLER, ACTION, DESCRICAO, DTH_CADASTRO, ICONE, STATUS) VALUES (1007, 1005, 'Dados do Cedente', '/Financeiro', '/Cedente', NULL, '2015-09-15T01:51:39.000000', 'fa-user', 'A');
-- INSERT INTO MENU (COD_MENU, COD_MENU_PAI, NOME, CONTROLLER, ACTION, DESCRICAO, DTH_CADASTRO, ICONE, STATUS) VALUES (1008, 1005, 'Cadastro de Agências', '/Financeiro', '/Banco', NULL, '2015-09-15T01:51:39.000000', 'fa-building', 'A');
-- COMMIT;

/***********************************************************  
MENU_USUARIO
***********************************************************/
CREATE TABLE MENU_USUARIO
(
	COD_RELACAO		  			INT NOT NULL 	AUTO_INCREMENT,
    COD_MENU		  			INT NOT NULL,
    COD_USUARIO					INT NOT NULL,
    PRIMARY KEY (COD_RELACAO),
    FOREIGN KEY (COD_MENU) REFERENCES MENU(COD_MENU),
    FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO(COD_USUARIO)
);

ALTER TABLE MENU_USUARIO AUTO_INCREMENT = 1000;

/***********************************************************  
INBOX
***********************************************************/
CREATE TABLE INBOX
(
	COD_INBOX		  			INT NOT NULL 	AUTO_INCREMENT,
    COD_USUARIO		  			INT NOT NULL,
    COD_USUARIO_REMETENTE		INT NOT NULL,
    COD_LOCAL					INT NOT NULL,   
    TITULO						VARCHAR(100) 	NULL,
    MENSAGEM					TEXT 			NULL,
	DTH_ENVIO   				DATETIME        DEFAULT CURRENT_TIMESTAMP, 
	DTH_LEITURA   				DATETIME        DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (COD_INBOX),
    FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO(COD_USUARIO)
);

ALTER TABLE INBOX AUTO_INCREMENT = 1000;

/***********************************************************  
PAIS
***********************************************************/
CREATE TABLE PAIS
(
	COD_PAIS		  			INT NOT NULL 	AUTO_INCREMENT,
    NOME	  					VARCHAR(100) 	NULL,
    PRIMARY KEY (COD_PAIS)
);

ALTER TABLE PAIS AUTO_INCREMENT = 1000;

INSERT INTO PAIS (NOME) VALUES ('Afeganistão');
INSERT INTO PAIS (NOME) VALUES ('África do Sul');
INSERT INTO PAIS (NOME) VALUES ('Akrotiri');
INSERT INTO PAIS (NOME) VALUES ('Albânia');
INSERT INTO PAIS (NOME) VALUES ('Alemanha');
INSERT INTO PAIS (NOME) VALUES ('Andorra');
INSERT INTO PAIS (NOME) VALUES ('Angola');
INSERT INTO PAIS (NOME) VALUES ('Anguila');
INSERT INTO PAIS (NOME) VALUES ('Antárctida');
INSERT INTO PAIS (NOME) VALUES ('Antígua e Barbuda');
INSERT INTO PAIS (NOME) VALUES ('Antilhas Neerlandesas');
INSERT INTO PAIS (NOME) VALUES ('Arábia Saudita');
INSERT INTO PAIS (NOME) VALUES ('Arctic Ocean');
INSERT INTO PAIS (NOME) VALUES ('Argélia');
INSERT INTO PAIS (NOME) VALUES ('Argentina');
INSERT INTO PAIS (NOME) VALUES ('Arménia');
INSERT INTO PAIS (NOME) VALUES ('Aruba');
INSERT INTO PAIS (NOME) VALUES ('Ashmore and Cartier Islands');
INSERT INTO PAIS (NOME) VALUES ('Atlantic Ocean');
INSERT INTO PAIS (NOME) VALUES ('Austrália');
INSERT INTO PAIS (NOME) VALUES ('Áustria');
INSERT INTO PAIS (NOME) VALUES ('Azerbaijão');
INSERT INTO PAIS (NOME) VALUES ('Baamas');
INSERT INTO PAIS (NOME) VALUES ('Bangladeche');
INSERT INTO PAIS (NOME) VALUES ('Barbados');
INSERT INTO PAIS (NOME) VALUES ('Barém');
INSERT INTO PAIS (NOME) VALUES ('Bélgica');
INSERT INTO PAIS (NOME) VALUES ('Belize');
INSERT INTO PAIS (NOME) VALUES ('Benim');
INSERT INTO PAIS (NOME) VALUES ('Bermudas');
INSERT INTO PAIS (NOME) VALUES ('Bielorrússia');
INSERT INTO PAIS (NOME) VALUES ('Birmânia');
INSERT INTO PAIS (NOME) VALUES ('Bolívia');
INSERT INTO PAIS (NOME) VALUES ('Bósnia e Herzegovina');
INSERT INTO PAIS (NOME) VALUES ('Botsuana');
INSERT INTO PAIS (NOME) VALUES ('Brasil');
INSERT INTO PAIS (NOME) VALUES ('Brunei');
INSERT INTO PAIS (NOME) VALUES ('Bulgária');
INSERT INTO PAIS (NOME) VALUES ('Burquina Faso');
INSERT INTO PAIS (NOME) VALUES ('Burúndi');
INSERT INTO PAIS (NOME) VALUES ('Butão');
INSERT INTO PAIS (NOME) VALUES ('Cabo Verde');
INSERT INTO PAIS (NOME) VALUES ('Camarões');
INSERT INTO PAIS (NOME) VALUES ('Camboja');
INSERT INTO PAIS (NOME) VALUES ('Canadá');
INSERT INTO PAIS (NOME) VALUES ('Catar');
INSERT INTO PAIS (NOME) VALUES ('Cazaquistão');
INSERT INTO PAIS (NOME) VALUES ('Chade');
INSERT INTO PAIS (NOME) VALUES ('Chile');
INSERT INTO PAIS (NOME) VALUES ('China');
INSERT INTO PAIS (NOME) VALUES ('Chipre');
INSERT INTO PAIS (NOME) VALUES ('Clipperton Island');
INSERT INTO PAIS (NOME) VALUES ('Colômbia');
INSERT INTO PAIS (NOME) VALUES ('Comores');
INSERT INTO PAIS (NOME) VALUES ('Congo-Brazzaville');
INSERT INTO PAIS (NOME) VALUES ('Congo-Kinshasa');
INSERT INTO PAIS (NOME) VALUES ('Coral Sea Islands');
INSERT INTO PAIS (NOME) VALUES ('Coreia do Norte');
INSERT INTO PAIS (NOME) VALUES ('Coreia do Sul');
INSERT INTO PAIS (NOME) VALUES ('Costa do Marfim');
INSERT INTO PAIS (NOME) VALUES ('Costa Rica');
INSERT INTO PAIS (NOME) VALUES ('Croácia');
INSERT INTO PAIS (NOME) VALUES ('Cuba');
INSERT INTO PAIS (NOME) VALUES ('Dhekelia');
INSERT INTO PAIS (NOME) VALUES ('Dinamarca');
INSERT INTO PAIS (NOME) VALUES ('Domínica');
INSERT INTO PAIS (NOME) VALUES ('Egipto');
INSERT INTO PAIS (NOME) VALUES ('Emiratos Árabes Unidos');
INSERT INTO PAIS (NOME) VALUES ('Equador');
INSERT INTO PAIS (NOME) VALUES ('Eritreia');
INSERT INTO PAIS (NOME) VALUES ('Eslováquia');
INSERT INTO PAIS (NOME) VALUES ('Eslovénia');
INSERT INTO PAIS (NOME) VALUES ('Espanha');
INSERT INTO PAIS (NOME) VALUES ('Estados Unidos');
INSERT INTO PAIS (NOME) VALUES ('Estónia');
INSERT INTO PAIS (NOME) VALUES ('Etiópia');
INSERT INTO PAIS (NOME) VALUES ('Faroé');
INSERT INTO PAIS (NOME) VALUES ('Fiji');
INSERT INTO PAIS (NOME) VALUES ('Filipinas');
INSERT INTO PAIS (NOME) VALUES ('Finlândia');
INSERT INTO PAIS (NOME) VALUES ('França');
INSERT INTO PAIS (NOME) VALUES ('Gabão');
INSERT INTO PAIS (NOME) VALUES ('Gâmbia');
INSERT INTO PAIS (NOME) VALUES ('Gana');
INSERT INTO PAIS (NOME) VALUES ('Gaza Strip');
INSERT INTO PAIS (NOME) VALUES ('Geórgia');
INSERT INTO PAIS (NOME) VALUES ('Geórgia do Sul e Sandwich do Sul');
INSERT INTO PAIS (NOME) VALUES ('Gibraltar');
INSERT INTO PAIS (NOME) VALUES ('Granada');
INSERT INTO PAIS (NOME) VALUES ('Grécia');
INSERT INTO PAIS (NOME) VALUES ('Gronelândia');
INSERT INTO PAIS (NOME) VALUES ('Guame');
INSERT INTO PAIS (NOME) VALUES ('Guatemala');
INSERT INTO PAIS (NOME) VALUES ('Guernsey');
INSERT INTO PAIS (NOME) VALUES ('Guiana');
INSERT INTO PAIS (NOME) VALUES ('Guiné');
INSERT INTO PAIS (NOME) VALUES ('Guiné Equatorial');
INSERT INTO PAIS (NOME) VALUES ('Guiné-Bissau');
INSERT INTO PAIS (NOME) VALUES ('Haiti');
INSERT INTO PAIS (NOME) VALUES ('Honduras');
INSERT INTO PAIS (NOME) VALUES ('Hong Kong');
INSERT INTO PAIS (NOME) VALUES ('Hungria');
INSERT INTO PAIS (NOME) VALUES ('Iémen');
INSERT INTO PAIS (NOME) VALUES ('Ilha Bouvet');
INSERT INTO PAIS (NOME) VALUES ('Ilha do Natal');
INSERT INTO PAIS (NOME) VALUES ('Ilha Norfolk');
INSERT INTO PAIS (NOME) VALUES ('Ilhas Caimão');
INSERT INTO PAIS (NOME) VALUES ('Ilhas Cook');
INSERT INTO PAIS (NOME) VALUES ('Ilhas dos Cocos');
INSERT INTO PAIS (NOME) VALUES ('Ilhas Falkland');
INSERT INTO PAIS (NOME) VALUES ('Ilhas Heard e McDonald');
INSERT INTO PAIS (NOME) VALUES ('Ilhas Marshall');
INSERT INTO PAIS (NOME) VALUES ('Ilhas Salomão');
INSERT INTO PAIS (NOME) VALUES ('Ilhas Turcas e Caicos');
INSERT INTO PAIS (NOME) VALUES ('Ilhas Virgens Americanas');
INSERT INTO PAIS (NOME) VALUES ('Ilhas Virgens Britânicas');
INSERT INTO PAIS (NOME) VALUES ('Índia');
INSERT INTO PAIS (NOME) VALUES ('Indian Ocean');
INSERT INTO PAIS (NOME) VALUES ('Indonésia');
INSERT INTO PAIS (NOME) VALUES ('Irão');
INSERT INTO PAIS (NOME) VALUES ('Iraque');
INSERT INTO PAIS (NOME) VALUES ('Irlanda');
INSERT INTO PAIS (NOME) VALUES ('Islândia');
INSERT INTO PAIS (NOME) VALUES ('Israel');
INSERT INTO PAIS (NOME) VALUES ('Itália');
INSERT INTO PAIS (NOME) VALUES ('Jamaica');
INSERT INTO PAIS (NOME) VALUES ('Jan Mayen');
INSERT INTO PAIS (NOME) VALUES ('Japão');
INSERT INTO PAIS (NOME) VALUES ('Jersey');
INSERT INTO PAIS (NOME) VALUES ('Jibuti');
INSERT INTO PAIS (NOME) VALUES ('Jordânia');
INSERT INTO PAIS (NOME) VALUES ('Kuwait');
INSERT INTO PAIS (NOME) VALUES ('Laos');
INSERT INTO PAIS (NOME) VALUES ('Lesoto');
INSERT INTO PAIS (NOME) VALUES ('Letónia');
INSERT INTO PAIS (NOME) VALUES ('Líbano');
INSERT INTO PAIS (NOME) VALUES ('Libéria');
INSERT INTO PAIS (NOME) VALUES ('Líbia');
INSERT INTO PAIS (NOME) VALUES ('Listenstaine');
INSERT INTO PAIS (NOME) VALUES ('Lituânia');
INSERT INTO PAIS (NOME) VALUES ('Luxemburgo');
INSERT INTO PAIS (NOME) VALUES ('Macau');
INSERT INTO PAIS (NOME) VALUES ('Macedónia');
INSERT INTO PAIS (NOME) VALUES ('Madagáscar');
INSERT INTO PAIS (NOME) VALUES ('Malásia');
INSERT INTO PAIS (NOME) VALUES ('Malávi');
INSERT INTO PAIS (NOME) VALUES ('Maldivas');
INSERT INTO PAIS (NOME) VALUES ('Mali');
INSERT INTO PAIS (NOME) VALUES ('Malta');
INSERT INTO PAIS (NOME) VALUES ('Isle of Man');
INSERT INTO PAIS (NOME) VALUES ('Marianas do Norte');
INSERT INTO PAIS (NOME) VALUES ('Marrocos');
INSERT INTO PAIS (NOME) VALUES ('Maurícia');
INSERT INTO PAIS (NOME) VALUES ('Mauritânia');
INSERT INTO PAIS (NOME) VALUES ('Mayotte');
INSERT INTO PAIS (NOME) VALUES ('México');
INSERT INTO PAIS (NOME) VALUES ('Micronésia');
INSERT INTO PAIS (NOME) VALUES ('Moçambique');
INSERT INTO PAIS (NOME) VALUES ('Moldávia');
INSERT INTO PAIS (NOME) VALUES ('Mónaco');
INSERT INTO PAIS (NOME) VALUES ('Mongólia');
INSERT INTO PAIS (NOME) VALUES ('Monserrate');
INSERT INTO PAIS (NOME) VALUES ('Montenegro');
INSERT INTO PAIS (NOME) VALUES ('Mundo');
INSERT INTO PAIS (NOME) VALUES ('Namíbia');
INSERT INTO PAIS (NOME) VALUES ('Nauru');
INSERT INTO PAIS (NOME) VALUES ('Navassa Island');
INSERT INTO PAIS (NOME) VALUES ('Nepal');
INSERT INTO PAIS (NOME) VALUES ('Nicarágua');
INSERT INTO PAIS (NOME) VALUES ('Níger');
INSERT INTO PAIS (NOME) VALUES ('Nigéria');
INSERT INTO PAIS (NOME) VALUES ('Niue');
INSERT INTO PAIS (NOME) VALUES ('Noruega');
INSERT INTO PAIS (NOME) VALUES ('Nova Caledónia');
INSERT INTO PAIS (NOME) VALUES ('Nova Zelândia');
INSERT INTO PAIS (NOME) VALUES ('Omã');
INSERT INTO PAIS (NOME) VALUES ('Pacific Ocean');
INSERT INTO PAIS (NOME) VALUES ('Países Baixos');
INSERT INTO PAIS (NOME) VALUES ('Palau');
INSERT INTO PAIS (NOME) VALUES ('Panamá');
INSERT INTO PAIS (NOME) VALUES ('Papua-Nova Guiné');
INSERT INTO PAIS (NOME) VALUES ('Paquistão');
INSERT INTO PAIS (NOME) VALUES ('Paracel Islands');
INSERT INTO PAIS (NOME) VALUES ('Paraguai');
INSERT INTO PAIS (NOME) VALUES ('Peru');
INSERT INTO PAIS (NOME) VALUES ('Pitcairn');
INSERT INTO PAIS (NOME) VALUES ('Polinésia Francesa');
INSERT INTO PAIS (NOME) VALUES ('Polónia');
INSERT INTO PAIS (NOME) VALUES ('Porto Rico');
INSERT INTO PAIS (NOME) VALUES ('Portugal');
INSERT INTO PAIS (NOME) VALUES ('Quénia');
INSERT INTO PAIS (NOME) VALUES ('Quirguizistão');
INSERT INTO PAIS (NOME) VALUES ('Quiribáti');
INSERT INTO PAIS (NOME) VALUES ('Reino Unido');
INSERT INTO PAIS (NOME) VALUES ('República Centro-Africana');
INSERT INTO PAIS (NOME) VALUES ('República Checa');
INSERT INTO PAIS (NOME) VALUES ('República Dominicana');
INSERT INTO PAIS (NOME) VALUES ('Roménia');
INSERT INTO PAIS (NOME) VALUES ('Ruanda');
INSERT INTO PAIS (NOME) VALUES ('Rússia');
INSERT INTO PAIS (NOME) VALUES ('Salvador');
INSERT INTO PAIS (NOME) VALUES ('Samoa');
INSERT INTO PAIS (NOME) VALUES ('Samoa Americana');
INSERT INTO PAIS (NOME) VALUES ('Santa Helena');
INSERT INTO PAIS (NOME) VALUES ('Santa Lúcia');
INSERT INTO PAIS (NOME) VALUES ('São Cristóvão e Neves');
INSERT INTO PAIS (NOME) VALUES ('São Marinho');
INSERT INTO PAIS (NOME) VALUES ('São Pedro e Miquelon');
INSERT INTO PAIS (NOME) VALUES ('São Tomé e Príncipe');
INSERT INTO PAIS (NOME) VALUES ('São Vicente e Granadinas');
INSERT INTO PAIS (NOME) VALUES ('Sara Ocidental');
INSERT INTO PAIS (NOME) VALUES ('Seicheles');
INSERT INTO PAIS (NOME) VALUES ('Senegal');
INSERT INTO PAIS (NOME) VALUES ('Serra Leoa');
INSERT INTO PAIS (NOME) VALUES ('Sérvia');
INSERT INTO PAIS (NOME) VALUES ('Singapura');
INSERT INTO PAIS (NOME) VALUES ('Síria');
INSERT INTO PAIS (NOME) VALUES ('Somália');
INSERT INTO PAIS (NOME) VALUES ('Southern Ocean');
INSERT INTO PAIS (NOME) VALUES ('Spratly Islands');
INSERT INTO PAIS (NOME) VALUES ('Sri Lanca');
INSERT INTO PAIS (NOME) VALUES ('Suazilândia');
INSERT INTO PAIS (NOME) VALUES ('Sudão');
INSERT INTO PAIS (NOME) VALUES ('Suécia');
INSERT INTO PAIS (NOME) VALUES ('Suíça');
INSERT INTO PAIS (NOME) VALUES ('Suriname');
INSERT INTO PAIS (NOME) VALUES ('Svalbard e Jan Mayen');
INSERT INTO PAIS (NOME) VALUES ('Tailândia');
INSERT INTO PAIS (NOME) VALUES ('Taiwan');
INSERT INTO PAIS (NOME) VALUES ('Tajiquistão');
INSERT INTO PAIS (NOME) VALUES ('Tanzânia');
INSERT INTO PAIS (NOME) VALUES ('Território Britânico do Oceano Índico');
INSERT INTO PAIS (NOME) VALUES ('Territórios Austrais Franceses');
INSERT INTO PAIS (NOME) VALUES ('Timor Leste');
INSERT INTO PAIS (NOME) VALUES ('Togo');
INSERT INTO PAIS (NOME) VALUES ('Tokelau');
INSERT INTO PAIS (NOME) VALUES ('Tonga');
INSERT INTO PAIS (NOME) VALUES ('Trindade e Tobago');
INSERT INTO PAIS (NOME) VALUES ('Tunísia');
INSERT INTO PAIS (NOME) VALUES ('Turquemenistão');
INSERT INTO PAIS (NOME) VALUES ('Turquia');
INSERT INTO PAIS (NOME) VALUES ('Tuvalu');
INSERT INTO PAIS (NOME) VALUES ('Ucrânia');
INSERT INTO PAIS (NOME) VALUES ('Uganda');
INSERT INTO PAIS (NOME) VALUES ('União Europeia');
INSERT INTO PAIS (NOME) VALUES ('Uruguai');
INSERT INTO PAIS (NOME) VALUES ('Usbequistão');
INSERT INTO PAIS (NOME) VALUES ('Vanuatu');
INSERT INTO PAIS (NOME) VALUES ('Vaticano');
INSERT INTO PAIS (NOME) VALUES ('Venezuela');
INSERT INTO PAIS (NOME) VALUES ('Vietname');
INSERT INTO PAIS (NOME) VALUES ('Wake Island');
INSERT INTO PAIS (NOME) VALUES ('Wallis e Futuna');
INSERT INTO PAIS (NOME) VALUES ('West Bank');
INSERT INTO PAIS (NOME) VALUES ('Zâmbia');
INSERT INTO PAIS (NOME) VALUES ('Zimbabué');
COMMIT;

/***********************************************************  
ESTADO
***********************************************************/
CREATE TABLE ESTADO
(
	COD_ESTADO		  			INT NOT NULL 	AUTO_INCREMENT,
	COD_PAIS		  			INT 			NOT NULL,
	SIGLA			  			VARCHAR(2)    NOT NULL,	
    NOME	  					VARCHAR(100) 	NULL,
    PRIMARY KEY (COD_ESTADO),
    FOREIGN KEY (COD_PAIS) REFERENCES PAIS(COD_PAIS)
);

ALTER TABLE ESTADO AUTO_INCREMENT = 1000;

﻿INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('AC',1035,'Acre');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('AL',1035,'Alagoas');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('AM',1035,'Amazonas');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('AP',1035,'Amapá');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('BA',1035,'Bahia');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('CE',1035,'Ceará');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('DF',1035,'Brasília (Distrito Federal)');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('ES',1035,'Espirito Santo');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('GO',1035,'Goias');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('MA',1035,'Maranhão');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('MG',1035,'Minas Gerais');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('MS',1035,'Mato Grosso do Sul');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('MT',1035,'Mato Grosso');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('PA',1035,'Pará');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('PB',1035,'Paraíba');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('PE',1035,'Pernambuco');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('PI',1035,'Piauí');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('PR',1035,'Paraná');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('RJ',1035,'Rio de Janeiro');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('RN',1035,'Rio Grande do Norte');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('RO',1035,'Rondônia');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('RR',1035,'Rorâima');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('RS',1035,'Rio Grande do Sul');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('SC',1035,'Santa Catarina');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('SE',1035,'Sergipe');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('SP',1035,'São Paulo');
INSERT INTO ESTADO (SIGLA,COD_PAIS,NOME) VALUES ('TO',1035,'Tocantins');
COMMIT;

/***********************************************************  
CIDADE
***********************************************************/
CREATE TABLE CIDADE
(
	COD_CIDADE		  			INT NOT NULL 	AUTO_INCREMENT,
	COD_ESTADO		  			INT 			NOT NULL,
    NOME	  					VARCHAR(100) 	NULL,
    PRIMARY KEY (COD_CIDADE),
    FOREIGN KEY (COD_ESTADO) REFERENCES ESTADO(COD_ESTADO)
);

ALTER TABLE CIDADE AUTO_INCREMENT = 1000;

/***********************************************************  
REGIAO
***********************************************************/
CREATE TABLE REGIAO
(
	COD_REGIAO		  			INT NOT NULL 	AUTO_INCREMENT,
	COD_PAIS		  			INT 			NOT NULL,
    NOME	  					VARCHAR(100) 	NULL,
    PRIMARY KEY (COD_REGIAO),
    FOREIGN KEY (COD_PAIS) REFERENCES PAIS(COD_PAIS)
);

ALTER TABLE REGIAO AUTO_INCREMENT = 1000;

INSERT INTO REGIAO (COD_PAIS,NOME) VALUES (1035,'Centro-Oeste');
INSERT INTO REGIAO (COD_PAIS,NOME) VALUES (1035,'Nordeste');
INSERT INTO REGIAO (COD_PAIS,NOME) VALUES (1035,'Norte');
INSERT INTO REGIAO (COD_PAIS,NOME) VALUES (1035,'Sul');
INSERT INTO REGIAO (COD_PAIS,NOME) VALUES (1035,'Sudeste');
COMMIT;

/***********************************************************  
BANCO
***********************************************************/
CREATE TABLE BANCO
(
	COD_BANCO		  			INT NOT NULL 	AUTO_INCREMENT,
    NOME	  					VARCHAR(100) 	NOT NULL,
	WEBSITE			  			VARCHAR(100) 	NULL,
	SIGLA			  			VARCHAR(100) 	NULL,
	FLAG_TIPO		  			CHAR(1) 		NULL,
	STATUS	  					CHAR(1) 		NOT NULL,
    PRIMARY KEY (COD_BANCO)
);

ALTER TABLE BANCO AUTO_INCREMENT = 1000;

INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DO BRASIL S.A. BANCO DO BRASIL S BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO CENTRAL DO BRASIL BACEN BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DA AMAZONIA S.A. BASA BCO', 'A', 'A', '1', 'a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DO NORDESTE DO BRASIL S.A. BNB BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO NACIONAL DE CREDITO COOPERATIVO S.A. BNCC INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO NACIONAL DE DESENV.ECONOMICO E SOCIAL BNDES BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO SANTANDER BANESPA S.A. SANTANDER BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SECRETARIA DO TESOURO NACIONAL - MF STN BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CREDIT SUISSE HEDGING-GRIFFO CORRETORA S.A. CRED.HED-GRIFFO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BI STANDARD BI STANDARD BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SENSO CORRETORA CAMBIO E VALORES MOBILIARIOS SC SENSO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('NATIXIS BRASIL S.A. BANCO MULTIPLO NATIXIS BRASIL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO AZTECA DO BRASIL S.A. AZTECA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DO ESTADO DE ALAGOAS S.A. PRODUBAN INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DO ESTADO DO ESPIRITO SANTO S.A. BANESTES BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DE CREDITO REAL DE MINAS GERAIS S.A. CREDIREAL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DE DESENVOLVIMENTO DE MINAS GERAIS BDMG BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DE PERNAMBUCO S.A.- BANDEPE BANDEPE BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO ALFA S.A. ALFA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DO ESTADO DO ACRE S.A. BANACRE BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BANEB S.A. BANEB BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BANERJ S.A. BANERJ BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('PARAIBAN-BANCO DO ESTADO DA PARAIBA S.A. PARAIBAN BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BEG S.A. BEG BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DO ESTADO DE MATO GROSSO S.A. BEMAT BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO SANTANDER BANESPA S.A. SANTANDER BANSP S BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DO ESTADO DO AMAZONAS S.A. BEA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DO ESTADO DO CEARA S.A. BEC BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BRADESCO BBI BRADESCO BBI BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DO ESTADO DO PARA S.A. BANPARA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BANESTADO S.A. BANESTADO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DO ESTADO DO PIAUI S/A BEP BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO CARGILL S.A. CARGILL S.A. BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DO ESTADO DO RIO GRANDE DO SUL S.A. BANRISUL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO J.SAFRA S.A. J.SAFRA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DO ESTADO DO RIO GRANDE DO NORTE S/A BANDERN INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BVA S.A BVA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO OPPORTUNITY S.A. B.OPPORTUNITY BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO REGIONAL DE DESENV.DO EXTREMO SUL S.A. BRDE INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DO ESTADO DE SERGIPE S.A. BANESE BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BEMGE S.A. BEMGE BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DE DESENV.DO ESTADO DA BAHIA S.A. DESENBANCO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DE DESENV.DO ESTADO DE SAO PAULO S.A. BADESP INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANRISUL S/A - DESIN BANRISUL-DESIN INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('AGENCIA CATARINENSE DE FOMENTO BADESC INST','','','','a'); 
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DO ESTADO DE RONDONIA S.A. BERON INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CONFIDENCE CORRETORA DE CAMBIO S.A SC CONFIDENCE BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO ABB S.A. BANCO ABB S.A. BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('HIPERCARD BANCO MULTIPLO S.A HIPERCARD BANCO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO IBI S.A.-BANCO MULTIPLO IBI BANCO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('GOLDMAN SACHS DO BRASIL BANCO MULTIPLO SA GOLDMAN SACHS BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('LEMON BANK BANCO MULTIPLO LEMON BANK BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO MORGAN STANLEY DEAN WITTER S.A. MORGAN STNALEY BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BANEB S.A. BANCO BANEB BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BPN BRASIL BANCO MULTIPLO S.A BPN BRASIL BM BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BRB-BANCO DE BRASILIA S.A. BRB BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('LINK SA CORRETORA DE CAMBIO TITUL E VAL MOBIL LINK SA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO RURAL MAIS S.A. RURAL MAIS BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO POPULAR DO BRASIL BANCO POPULAR BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO J.SAFRA S.A. J.SAFRA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO CR2 S.A. BANCO CR2 S.A. BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('KDB DO BRASIL KDB DO BRASIL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO INTERMEDIUM S.A INTERMEDIUM BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BES INVESTIMENTO DO BRASIL S.A. BI-BES E.SANTO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('JBS BANCO S.A. JBS BANCO S.A. BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('B&T ASSOCIADOS CORRETORA DE CAMBIO LTDA SCBT ASSOCIADOS BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CONCORDIA BANCO S.A. CONCORDIA BANCO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO TOPAZIO S.A. BANCO TOPAZIO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DA CHINA BRASIL S.A. B.CHINA BRASIL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CC UNICRED NORTE DO PARANA CC UN.NORTE PR BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CC CECRED CC CECRED BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('OBOE CREDITO-FINANCIAMENTO E INVESTIMENTO SA SCFI OBOE BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CC UNICRED CENTRAL SANTA CATARINA CC UNICRED - SC BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO RANDON S.A BANCO RANDON SA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA CREDITO RURAL REGIAO DA MOGIANA C.R.R.MOGIANA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('UNICRED CENTRAL SAO PAULO CC UNICRED SP BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CC UNICRED CENTRAL RS UNICRED RS BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BRICKEL S.A CREDITO, FINANCIAMENTO E INVEST. SCFI BRICKELL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('POLOCRED SOCIEDADE CREDITO MICROEMPREENDEDOR SCM POLOCRED BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO PETRA S.A. BANCO PETRA S.A BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO CONFIDENCE DE CAMBIO S.A. BCAM CONFIDENCE BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BM&F DE SERV.DE LIQUIDACAO E CUSTODIA BANCO BM&F BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CC CENTRAL CREDI CC CENTRALCREDI BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CREDICOROL COOPERATIVA DE CREDITO RURAL CC CREDICOROL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. CENTRAL DAS UNICRED(S) ESTADOS PR E MS UNICRED PR/MS BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('DTVM RENANSCENCA DTVM RENANSCENC BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SC EBS SC EBS BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CAIXA ECONOMICA FEDERAL CEF BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO ITABANCO S.A. ITABANCO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BBM S.A. BBM BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO CREDIBANCO S/A CREDIBANCO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('OLIVEIRA TRUST DIST. DE TITULOS E VALORES SA. DTVM OLIVEIRA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('MAGLIANO S/A CORRETORA DE CAMBIO VALORES MOB SC MAGLIANO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO UNICO UNICO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('ADVANCED CORRETORA DE CAMBIO LTDA SC ADVANCED BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DE INVESTIMENTO BRADESCO B.I.BRADESCO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DO NORDESTE DO BRASIL S/A. BNB INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DE INVESTIMENTO MULTIPLIC B.I.MULTLIPIC INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANK OF AMERICA-BRASIL S.A. BANK OF AMERICA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CAIXA ECONOMICA DO ESTADO DE MINAS GERAIS MINASCAIXA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DE INVESTIMENTOS GARANTIA S/A BIG INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BI GERACAO FUTURO BI GERAC.FUTURO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('HSBC INVESTIMENT BANK BRASIL S.A. HSBC BRASIL S.A BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO FINASA S.A. FINASA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO ITAU-BBA S.A. BANCO ITAU-BBA. BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO FINANCIAL PORTUGUES FINAN.PORTUGUES BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO FICRISA AXELRUD S.A. FICRISA AXELRUD BCO ','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO AXIAL S.A. AXIAL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BRADESCO CARTOES BRADESCO CARTOE BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO SUL AMERICA S/A SUL AMERICA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BTG PACTUAL S.A. BTG PACTUAL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('DRESDNER BANK LATEINAMERIKA AKTIENGESELLSCH DRESDNER BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO SISTEMA S/A SISTEMA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO MATONE S.A. MATONE BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO ARBI S.A. ARBI BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DIBENS S.A. DIBENS BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO COMERCIAL E DE INVESTIM. SUDAMERIS S/A SUDAMERIS BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO REGIONAL MALCON S/A-COM.E DE CRED.CONS. MALCON BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO JOHN DEERE S.A. JOHN DEERE BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BONSUCESSO S/A BONSUCESSO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO ZOGBI S.A. ZOGBI BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO CHASE FLEMING S.A. BANCO FLEMING BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO CALYON BRASIL S.A CALYON BRASIL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO FIBRA S/A FIBRA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BRASCAN S/A BRASCAN BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO ICATU S.A. ICATU BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO CRUZEIRO DO SUL S/A CRUZEIRO DO SUL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('UNICARD BANCO MULTIPLO S.A. UNICARD B.MULT. BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BOAVISTA INTERATLANTICO S.A. BOAVISTA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO INTERPART S/A INTERPART BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO GE CAPITAL S.A. GE CAPITAL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO LAVRA S/A LAVRA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANK OF AMERICA LIBERAL S.A. LIBERAL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BRADESCO SA BRADESCO S BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DE CREDITO REAL DE MINAS GERAIS S/A CREDIREAL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO CLASSICO S.A. CLASSICO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO EUROINVEST S.A.-EUROBANCO EUROINVEST BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO MAXIMA S.A. BANCO MAXIMA SA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO CIDADE S.A. BANCO CIDADE BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO ABC BRASIL S.A. ABC-BRASIL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO UBS S.A. BANCO UBS S.A. BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BOAVISTA INTERATLANTICO S.A. B.BOAVISTA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO INVESTCRED UNIBANCO S.A. INVESTCRED BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO SCHAHIN S.A. SCHAHIN BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CRED.RURAL DA REGIAO DE VARGINHA LTDA. CREDIVAR INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO FININVEST S.A. FININVEST BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('PARANA BANCO S.A. PARANA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO INDUSCRED S.A. INDUSCRED BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BOREAL S/A BOREAL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO CACIQUE S.A. CACIQUE BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO FATOR S.A FATOR BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO CEDULA S/A CEDULA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO REAL-ABN AMRO REAL-ABN AMRO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DE CREDITO NACIONAL S.A. BCN BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DE CREDITO REAL DO RIO G.DO SUL S.A. B.CRED.REAL RS BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DE LA NACION ARGENTINA NACIONARGENTINA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO COMERCIAL BANCESA S.A. BANCESA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BMG S.A. BMG BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO INDUSTRIAL E COMERCIAL S.A. BIC BANCO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO ECONOMICO S.A. ECONOMICO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO ITAU UNIBANCO S.A. ITAU UNIBANCO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO FRANCES E BRASILEIRO S.A. B.FRANCES/BRAS. BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO SUDAMERIS BRASIL S.A. SUDAMERIS BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO SANTANDER S.A. SANTANDER BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO SANTANDER BRASIL S.A. SANTANDERBRASIL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO ABN AMRO REAL S.A. ABN AMRO REAL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO SOCIETE GENERALE BRASIL S.A. SOCIETE GENERAL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO WESTLB DO BRASIL S.A. WESTLB BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO J.P.MORGAN S.A. J.P.MORGAN BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CRED.RURAL NOVA PETROPOLIS SICREDI-PIONEI. INST ','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO MERCANTIL DO BRASIL S.A. MERCANTIL DO B. BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO MERCANTIL DE SAO PAULO MERCANTIL DE SP BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BRADESCO FINANCIAMENTOS S.A. BRADESCO FINAC. BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('HSBC BANK BRASIL S.A.- BANCO MULTIPLO HSBC BANK S BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('UNIBANCO-UNIAO DE BANCOS BRASILEIROS S.A. UNIBANCO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO CAPITAL S.A. CAPITAL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CRED.RURAL VALE DO GORUTUBA LTDA. CREDIVAG INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO SAFRA S.A. SAFRA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO NOROESTE/SANTANDER S.A NOROESTE BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CRED.RURAL DA REGIAO MOGIANA SICOOB-CREDISAN INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO RURAL S.A. RURAL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DE TOKYO-MITSUBISHI BRASIL S.A. TOKYO-MITSUBIHI BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO SUMITOMO MITSUI BRASILEIRO S.A. SUMITOMO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('LLOYDS TSB BANK PLC LLOYDS BANK BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO CAIXA GERAL - BRASIL S.A. CAIXA GERAL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CITIBANK N.A. CITIBANK N.A BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('ITAU BANK ITAU BANK BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO WACHOVIA S.A. WACHOVIA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DE RORAIMA S.A. BANRORAIMA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('DEUTSCHE BANK S.A.BANCO ALEMAO DEUTSCHE BANK BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('JPMORGAN CHASE BANK JPMORGAN BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO FRANCES INTERNACIONAL (BRASIL)S.A. FRANCES INTERN. BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('ING BANK N.V. ING BANK N.V. BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO UNION - BRASIL S.A. UNION BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DE LA REPUBLICA ORIENTAL DEL URUGUAY REP.OR.URUGUAY BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DE LA PROVINCIA DE BUENOS AIRES PROVINCIA B.AIR BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO UNO-E BRASIL S.A. BANCO UNO S.A. BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO SANTANDER CENTRAL HISPANO CENTRO HISPANO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DE SANTANDER DE NEGOCIOS S.A. SANTANDER_NEGOC BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO CREDIT SUISSE FIRST BOSTON GARANTIA S. CREDIT SUISSE BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CRED.RURAL DE MARACAJU LTDA. SICREDIMARACA. INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO LUSO BRASILEIRO S/A LUSO BRASILEIRO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO INDUSTRIAL DO BRASIL S/A INDL.DO BRASIL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO SANTOS NEVES S/A SANTOS NEVES BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO VR S.A. VR BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO PAULISTA S/A PAULISTA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO GUANABARA S.A. GUANABARA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO PECUNIA S/A PECUNIA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO TENDENCIA S.A. TENDENCIA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO PANAMERICANO S/A PANAMERICANO SA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO ARAUCARIA S/A ARAUCARIA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO FICSA S/A FICSA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO INTERCAP S/A INTERCAP BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO RENDIMENTO S.A. RENDIMENTO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO TRIANGULO S/A TRIANGULO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO SOFISA S/A SOFISA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO PROSPER S/A PROSPER BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO ALVORADA S.A. BANCO ALVORADA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO PINE S.A. PINE BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO PEBB S.A. PEBB BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO ITAU UNIBANCO_HOLDING ITAU UNIBANCO_H BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO INDUSVAL S/A INDUSVAL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO A. J. RENNER S/A A.J.RENNER BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO VOTORANTIM S/A VOTORANTIM BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO MATRIX S/A MATRIX BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO PORTO REAL S/A PORTO REAL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CRED.RURAL VALE DO JAGUARI SICREDI-V.JAGU. INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO SANTOS S/A SANTOS BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SERTE/DIFUP 01 SERTE/DIFUP 01 INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SERTE/DIFUP 02 SERTE/DIFUP 02 INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SERTE/DIFUP 03 SERTE/DIFUP 03 INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DAYCOVAL S.A. DAYCOVAL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SERTE/DIFUP 05 SERTE/DIFUP 05 INST ','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SERTE/DIFUP 06 SERTE/DIFUP 06 INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SERTE/DIFUP 07 SERTE/DIFUP 07 INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SERTE/DIFUP 08 SERTE/DIFUP 08 INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SERTE/DIFUP 09 SERTE/DIFUP 09 INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SERTE/DIFUP 10 SERTE/DIFUP 10 INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SERTE/DIFUP 11 SERTE/DIFUP 11 INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SERTE/DIFUP 12 SERTE/DIFUP 12 INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SERTE/DIFUP 13 SERTE/DIFUP 13 INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SERTE/DIFUP 14 SERTE/DIFUP 14 INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SERTE/DIFUP 15 SERTE/DIFUP 15 INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BANIF PRIMUS S.A. BANIF PRIMUS BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO MAXINVEST S/A MAXINVEST BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO CREDIBEL S.A. CREDIBEL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO INTERIOR DE SAO PAULO S/A INTERIOR_SP BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO FINANSINOS S/A FINANSINOS BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO FONTE CINDAM S.A. FONTE CINDAM BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO MINAS S/A MINAS BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DAS NACOES S.A. NACOES BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO GERDAU S/A GERDAU BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO POTTENCIAL S/A POTTENCIAL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO THECA S/A THECA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO MORADA S/A MORADA BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BGN S/A BGN BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BARCLAYS S.A. BARCLAYS S.A. BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO RIBEIRAO PRETO S/A RIBEIRAO PRETO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO EQUATORIAL S/A EQUATORIAL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO SEMEAR S/A SEMEAR BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANKBOSTON, N.A. BOSTON N.A. BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO CITIBANK S/A CITIBANK S.A. BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO MODAL S/A MODAL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO RABOBANK INTERNATIONAL BRASIL S.A. RABOBANK BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO COOPERATIVO SICREDI S.A.- BANSICREDI SICREDI BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO SIMPLES S.A. BANCO SIMPLES BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('HSBC REPUBLIC BANC BRASIL SA-BANCO MULTIPLO HSCB REPUBLIC BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('DRESDNER BANK BRASIL S.A. BANCO MULTIPLO DRESDNER BRASIL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BNP PARIBAS BRASIL S.A. BNP PARIBAS BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('NBC BANK BRASIL S.A. NBC BANK BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO MERRILL LYNCH S/A BI MERRIL LYNCH BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO COOPERATIVO DO BRASIL S/A BANCOOB BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO KEB DO BRASIL S.A. KEB DO BRASIL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('NORDEA BANK_DANMARK NORDEA BANK BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BCR CRED. REAL BCR CRED.REAL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CENT.FOR.DE CANA REG.STABARBARA DOESTE CC.F.C.S.B.OEST INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CENT.DOS FORN.DE CANA DE PIRACICABA LTDA CC.F.C.PIRACICA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CENT.LAVRADORES CANA DE ACUCAR E RJ. CC.L.C.A RJ. INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CENT.DOS PLAN.CANA DE SERTAOZINHO LTDA CC.P.C.SERTAOZ INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA CREDITO CENTRAL DO PARANA LTDA. CCC.PARANA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL AGUDO LTDA. CCR.AGUDO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL ALTO JUCUI LTDA. CCR.ALT.JUCUI INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CRETITO RURAL AURIVERDE LTDA CCR.AURIVERDE INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL CELEIRO LTDA. CCR.CELEIRO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL COAMO LTDA. CCR.COAMO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL CONQUISTA LTDA CCR.CONQUISTA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPER.DE CREDITO RURAL DE AJURICABA LTDA CCR.AJURICABA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL DE ALEGRETE LTDA CCR.ALEGRETE INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL DE ASTORGA LTDA. CCR.ASTORGA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL DE CACADOR LTDA. CCR.CACADOR INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CREDITO RURAL DE CACAPAVA DO SUL LTDA CCR.CACAPAVA S. INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CRED.RURAL CARAZINHO E CHAPADA LTDA. CCR.CAR.E CHAP. INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CRED.RURAL DE CARLOS BARBOSA LTDA. CCR.C.BARBOSA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CRED. DE CERRO LARGO LTDA. CCR.C.LARGO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL DE COLORADO LTDA CCR.COLORADO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPER.DE CREDITO RURAL DE CRUZ ALTA LTDA. CCR.C.ALTA INST ','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CREDITO RURAL DE ENCANTADO LTDA. CCR.ENCANTADO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL DE ERECHIM LTDA. CCR.ERECHIM INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL DE ESPUMOSO_LTDA CCR.ESPUMOSO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CRED.RURAL DE FAXINAL DO SOTURNO LTDA CCR.F.SOTURNO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CRED.RURAL DE FREDERICO WESTPHALEN LTDA. CCR.F.WESTPHAL INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CRED.RURAL DE GETULIO VARGAS LTDA. CCR.G.VARGAS INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPER. DE CREDITO RURAL DE GUARAPUAVA LTDA. CCR.GURAUAVA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CRED. RURAL DE HORIZONTINA LTDA CCR.HORIZONTINA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CREDITO RURAL DE IBIRAIARAS LTDA. CCR.IBIRAIARAS INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL DE IBIRUBA LTDA. CCR.IBIRUBA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL DE ITABUNA LTDA. CCR.ITABUNA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CREDITO RURAL DE JACUTINGA LTDA. CCR.JACUTINGA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPER. RURAL DE JAGUARI LTDA COOP.R.JAGUARI INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CREDITO RURAL DE MANDAGUARI LTDA. CCR.MANDAGUARI INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL DE MARAU LTDA CCR.MARAU INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL DE MARILIA LTDA CCR.MARILIA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL DE MARINGA LTDA SICREDI MARINGA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CREDITO RURAL DE NOVA PALMA LTDA CCR PALMA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CRED. RURAL DE PALM. DAS MISSOES LTDA CCR PALMEIRA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CREDITO RURAL DE PASSO FUNDO LTDA CCR PASSO FUNDO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CRED. RURAL DE PRIMAV. DO LESTE LTDA CCR LESTE INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CREDITO RURAL DE RODEIO BONITO LTDA CCR BONITO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CRED. RURAL DE ROSARIO DO SUL LTDA CCR DO SUL INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CRED. RURAL DE SANANDUVA LTDA CCR SANANDUVA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CRED.RURAL DE SANT. BARB. DO SUL LTDA CCR DO SUL INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CRED. RURAL DO VALE DO RIO PARDO CCR RIO PARDO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CRED. RURAL DE SANTA MARIA LTDA CCR SANTA MARIA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CREDITO RURAL DE SANTIAGO LTDA CCR SANTIAGO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CRED. RURAL DE SANTO ANGELO LTDA CCR ANGELO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CRED.RURAL DE SAO MIGUEL D`OESTE LTDA CCR D`OESTE INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CRED.RURAL DE MARINGA SICREDIMARINGA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CCR DE SERRINHA DE RESPONSABILIDADE LTDA CCR SERRINHA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL DE SOLEDADE LTDA CCR SOLEDADE INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA CREDITO RURAL NORTE CATARINENSE CRN CATARINENSE INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CREDITO RURAL TRES DE MAIO LTDA CCR MAIO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CREDITO RURAL DE VIDEIRA LTDA CCR VIDEIRA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CRED.RURAL DO NORTE DE MINAS LTDA CCR MINAS INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CRED. RURAL DO OESTE DE MATO GROSSO LTDA CCR DO OESTE MT INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CRED.RURAL DO SUL DE MATO GROSSO LTDA CCR SUL DE MT INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CRED.RURAL DO VALE DO CANOINHAS LTDA CCR V CANOINHAS INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CRED.RURAL DO NORTE DE MINAS LTDA. CREDINOR INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CRED. RURAL DO VALE DO RIO DOCE LTDA CCR V. RIO DOCE INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CRED.RURAL CAFEICUTS. REG.VARGINHA LTDA CCR R.VARGINHA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CRED.RUR.CAFEICTS.AGROPECTS.GUAXUPE LTDA CCR GUAXUPE INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CRED.RUR.PLANTADS.CANA ACUC.GUARIBA LTDA CCR GUARIBA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CREDITO RURAL LUCAS DO RIO VERDE LTDA CCR L.RIO VERDE INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL MISSOES LTDA CCR MISSOES INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CREDITO RURAL NOVA PETROPOLIS LTDA CCR N.PETROPLS. INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CREDITO RURAL OURO BRANCO LTDA CCR OURO BRANCO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL PANAMBI LTDA CCR PANAMBI INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CREDITO RURAL PARANAPANEMA LTDA CCR PARANAPANE. INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL PESTANENSE LTDA CCR PESTANENSE INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL SANTA ROSA LTDA CCR SANTA ROSA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CREDITO RURAL SANTOAUGUSTENSE LTDA CCR STOAUGUSTSE INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL SARANDI LTDA CCR SARANDI INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL SORRISO LTDA CCR SORRISO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL TAPERENSE LTDA CCR TAPERENSE INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CREDITO RURAL TRES FRONTEIRAS LTDA CCR T.FRONTEIRS INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CREDITO RURAL VALE DO TIBAGI LTDA CCR V.DO TIBAGI INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA ITAQUIENSE DE CREDITO RURAL LTDA CCR ITAQUIENSE INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CRED RURAL DE SAO JOAO LTDA CCRSJ INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CRED VALE DO RIO DO PEIXE LTDA CCVRP INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CRED RURAL CRAVIL LTDA CCRC INST ','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CRED RURAL DO NORTE CATARINENSE LTDA CCRNC INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CRED RURAL ITAIPU LTDA CCRI INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.REG.CRED.RURAL DO VALE RIO GRANDE LTDA. CREDICOPERVALE INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CAIXA ESTADUAL S.A. AGENCIA DE FOMENTO/RS AFSUL INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CRED.DOS PLANT.DE CANA DE SERTAOZINHO COCRED INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CENTRAL DE CRED.RURAL DO EST.DE S.PAULO SICOOB-SP-COCE. INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL DE CAMPOS NOVOS CREDICAMPOS INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CRED.RURAL OESTE CATARINENESE OESTECREDI INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL DE SAO LOURENCO SICOOB S.LOUREN INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL ALFA CREDIALFA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL JACINTO MACHADO SICOOB/CREDIJA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL NOROESTE SICOOB NOROESTE INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CORRETORA SOUZA BARROS CAMBIO E TITULOS S.A. SC SOUZA BARROS BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('ERSTE BANK DER OESTERREICHISCHEN SPARKASSEN SPARKASSEN BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BMF ATIVOS BMF ATIVOS BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BMF BOVESPA - CBLC BMF BOVESPA-CBL BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BMF CAMBIO BMF CAMBIO BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BMF DERIVATIVOS BMF DERIVATIVOS BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CETIP CETIP BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CIP SILOC CIP SILOC BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CIP SITRAF CIP SITRAF BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CRED.RURAL DE CASSIA LTDA. CREDICASSIA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CREDITO RURAL ALTO URUGUAI CATARINENSE COOP.ALTO URUG. INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA CREDITO RURAL CARMO DO PARANAIBA COOP.PARANAIBA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO BAMENRINDUS DO BRASIL-EM LIQUIDACAO B.BAMERINDUS BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO MAXI ALFA DE LIVRE ADM CCR DE CHAPECO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.REG.CRED.SUDOESTE MIN. E NORDESTE PAULIS SICOOB INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CRED.RURAL PLANT.CANA ZONA MATA LTDA COOP.CANA Z.M. INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('FUNDACAO VISCONDE DE CABO FRIO F. V.CABO FRIO INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.CENTRAL CRED.RURAL DO RIO G. DO SUL LTDA COCECRER - RS INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('INSTITUTO ECON. AGRICO - SEC. AGRIC. SP IEA/SP INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COMPANHIA NACIONAL DE ABASTECIMENTO - CONAB CONAB INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SELIC SELIC BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('DEPART. NACIONAL DE ESTRADAS DE RODAGEM DNER INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('INSTITUTO BRASILEIRO DO CAFE IBC INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('REMUNERACAO DA CAMPO A SER RESSARCIDA P/ MA PRODECER II INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('UNIVERSIDADE FEDERAL DE VICOSA UNIV.FED.VICOSA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('FUNDACAO NORTE-MINEIRA DE ENSINO SUPERIOR F.NORTE-MIN. ES INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('ORGANIZACAO DAS COOPERATIVAS BRASILEIRAS ORG.COOP. BRAS. INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('FUNDACAO ARTHUR BERNARDES F. A. BERNARDES INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('FUND. DE INTEG.,DESENV. EDUC. NOROESTE ESTADO FIDENE INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CREDITO RURAL DO OESTE LTDA. CCR INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CREDITO AGROPECUARIO DO OESTE LTDA CCA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. CENTRAL DE CREDITO DO PARANA S.A. CCC INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CREDITO RURAL DE JULIO DE CASTILHOS CCR INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CREDITO RURAL DE SAO BORJA LTDA CCR INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CREDITO RURAL DE CAMPO NOVO LTDA CCR INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CREDITO RURAL DE CANDELARIA LTDA. CCR INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CREDITO RURAL DE CAICHOERENSE LTDA. CCR INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CREDITO RURAL DE CRISSIUMAL LTDA. CCR INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SAM - SOC.ARREND.MERCANTIL -CITIBANK-LEASING SAM-CITIBANK INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SECRETARIA DE TECNOLOGIA INDUSTRIAL - MIC MIC/STI INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('FINANCIADORA DE ESTUDOS E PROJETOS FINEP INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CONSELHO NACIONAL DE DESENVOLVIMENTO URBANO CNDU INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SUPERINTENDENCIA DO DESENV. DO NORDESTE SUDENE INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('SECRETARIA DE PLANEJAMENTO / PR SEPLAN/PR INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COMESTIL COM. IND. LTDA COMESTIL LTDA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('CINDRE IND. COM. LTDA CINDRE LTDA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('INDUSTRIA DE OLEOS POMPEIA LTDA OLEOS POMPEIA INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP. DE CREDITO RURAL DE PARNAMBI LTDA. CCR INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP.DE CREDITO RURAL DE TENENTE PORTELA LTDA CCR INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANCO DE BOSTON INTERNACIONAL BCO.BOSTON INT. BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('IBJ WHITERAL BANK AND TRUST COMPANY IBJ WHITERAL BCO ','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('WARBURG DILLON READ WARBURG DI.READ BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('N.M. ROTSCHILD & SONS LIMITED N.M. ROTSCHILD BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('BANK ONE BANK ONE BCO','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOPERATIVA DE CREDITO RURAL LINENSE CCR LINENSE INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP CENT CRED RURAL INTER SOLI CRESOL CENTRA CRESOL CENTRAL INST','','','','a');
INSERT INTO BANCO (NOME, WEBSITE, SIGLA, FLAG_TIPO, STATUS) VALUES ('COOP CENT CRED RURAL INTER SOLI CRESOL-BASER CRESOL BASER INST','','','','a');
COMMIT;

/***********************************************************  
CEDENTE
***********************************************************/
CREATE TABLE CEDENTE
(
	COD_CEDENTE		  			INT NOT NULL 	AUTO_INCREMENT,
	COD_BANCO					INT 			NOT NULL,
    NOME	  					VARCHAR(100) 	NOT NULL,
    ENDERECO					VARCHAR(100) 	NOT NULL,
	NUMERO						NUMERIC(5)      DEFAULT 0,
	BAIRRO						VARCHAR(100) 	NOT NULL,
	CIDADE						VARCHAR(100) 	NOT NULL,
	UF							CHAR(2) 		NOT NULL,
	CEP							VARCHAR(10) 	NULL,	
	DTH_NASCIMENTO				DATETIME        NOT NULL,    
	CPF_CNPJ					VARCHAR(30) 	NULL,
	INSTRUCAO_BOLETO			VARCHAR(300) 	NULL,
	NUM_AGENCIA					VARCHAR(10) 	NOT NULL,
	NUM_CONTA_CORRENTE			VARCHAR(10) 	NOT NULL,
	STATUS	  					CHAR(1) 		NOT NULL,
    PRIMARY KEY (COD_CEDENTE),
    FOREIGN KEY (COD_BANCO) REFERENCES BANCO(COD_BANCO)
);

ALTER TABLE CEDENTE AUTO_INCREMENT = 1000;

/***********************************************************  
MENSAGEM
***********************************************************/
CREATE TABLE MENSAGEM
(
	COD_MENSAGEM	  			INT NOT NULL 	AUTO_INCREMENT,
	COD_AUTOR					INT 			NOT NULL,
    TITULO	  					VARCHAR(100) 	NOT NULL,
    TEXTO						TEXT		 	NOT NULL,
    DTH_CRIACAO              	DATETIME        DEFAULT CURRENT_TIMESTAMP, 
    DTH_ENVIO	              	DATETIME        NULL, 
    PRIMARY KEY (COD_MENSAGEM),
    FOREIGN KEY (COD_AUTOR) REFERENCES USUARIO(COD_USUARIO)
);

ALTER TABLE MENSAGEM AUTO_INCREMENT = 1000;

/***********************************************************  
MENSAGEM_ENVIADA
***********************************************************/
CREATE TABLE MENSAGEM_ENVIADA
(
	COD_ENVIO					INT NOT NULL 	AUTO_INCREMENT,
	COD_MENSAGEM				INT 			NOT NULL,
	COD_AUTOR					INT 			NOT NULL,
	COD_REMETENTE				INT 			NOT NULL,
	STATUS_AUTOR				CHAR(1) 		NOT NULL, -- BOX: 1 ENTRADA, 2 ENVIADOS, 3 LIXEIRA
	STATUS_REMETENTE			CHAR(1) 		NOT NULL, -- BOX: 1 ENTRADA, 2 ENVIADOS, 3 LIXEIRA
	PRIMARY KEY (COD_ENVIO),
	FOREIGN KEY (COD_MENSAGEM) REFERENCES MENSAGEM(COD_MENSAGEM)
);

ALTER TABLE MENSAGEM_ENVIADA AUTO_INCREMENT = 1000;

/***********************************************************  
DOMINIO
***********************************************************/
CREATE TABLE DOMINIO
(
	COD_DOMINIO		  			INT NOT NULL 	AUTO_INCREMENT,
    NOME		  			    VARCHAR(100) 	NOT NULL,
    TIPO		  			    VARCHAR(50) 	NOT NULL,
	DESCRICAO    		        TEXT 			NULL,
    STATUS					    CHAR(1) 		NOT NULL, -- A - ATIVO, I - INATIVO
    PRIMARY KEY (COD_DOMINIO)
);

ALTER TABLE DOMINIO AUTO_INCREMENT = 1000;

/***********************************************************  
WEBSITE
***********************************************************/
CREATE TABLE WEBSITE
(
    COD_WEBSITE                  INT NOT NULL     AUTO_INCREMENT,
    LINK                         VARCHAR(200)     NOT NULL,
    DESCRICAO                    TEXT            NULL,
    STATUS                       CHAR(1)            NOT NULL,
    PRIMARY KEY (COD_WEBSITE)
);

ALTER TABLE WEBSITE AUTO_INCREMENT = 1000;

/***********************************************************  
ASPNET_APPLICATIONS
***********************************************************/
CREATE TABLE ASPNET_APPLICATIONS (
  APPLICATIONNAME TEXT,
  APPLICATIONID INT(11) NOT NULL AUTO_INCREMENT,
  DESCRIPTION TEXT,
  PRIMARY KEY (APPLICATIONID)
);

/***********************************************************  
ASPNET_PROFILE
***********************************************************/
CREATE TABLE ASPNET_PROFILE (
  USERID BIGINT(20) DEFAULT NULL,
  PROPERTYNAMES TEXT,
  PROPERTYVALUESSTRING TEXT,
  LASTUPDATEDDATE DATETIME DEFAULT NULL
);
 
/***********************************************************  
MY_ASPNET_APPLICATIONS
***********************************************************/
CREATE TABLE MY_ASPNET_APPLICATIONS (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(256) DEFAULT NULL,
  DESCRIPTION VARCHAR(256) DEFAULT NULL,
  PRIMARY KEY (ID)
);

/***********************************************************  
MY_ASPNET_MEMBERSHIP
***********************************************************/
CREATE TABLE MY_ASPNET_MEMBERSHIP (
  USERID INT(11) NOT NULL DEFAULT '0',
  EMAIL VARCHAR(128) DEFAULT NULL,
  COMMENT VARCHAR(255) DEFAULT NULL,
  PASSWORD VARCHAR(128) NOT NULL,
  PASSWORDKEY CHAR(32) DEFAULT NULL,
  PASSWORDFORMAT TINYINT(4) DEFAULT NULL,
  PASSWORDQUESTION VARCHAR(255) DEFAULT NULL,
  PASSWORDANSWER VARCHAR(255) DEFAULT NULL,
  ISAPPROVED TINYINT(1) DEFAULT NULL,
  LASTACTIVITYDATE DATETIME DEFAULT NULL,
  LASTLOGINDATE DATETIME DEFAULT NULL,
  LASTPASSWORDCHANGEDDATE DATETIME DEFAULT NULL,
  CREATIONDATE DATETIME DEFAULT NULL,
  ISLOCKEDOUT TINYINT(1) DEFAULT NULL,
  LASTLOCKEDOUTDATE DATETIME DEFAULT NULL,
  FAILEDPASSWORDATTEMPTCOUNT INT(10) UNSIGNED DEFAULT NULL,
  FAILEDPASSWORDATTEMPTWINDOWSTART DATETIME DEFAULT NULL,
  FAILEDPASSWORDANSWERATTEMPTCOUNT INT(10) UNSIGNED DEFAULT NULL,
  FAILEDPASSWORDANSWERATTEMPTWINDOWSTART DATETIME DEFAULT NULL,
  PRIMARY KEY (USERID)
);

/***********************************************************  
MY_ASPNET_PROFILES
***********************************************************/
CREATE TABLE MY_ASPNET_PROFILES (
  USERID INT(11) NOT NULL,
  VALUEINDEX LONGTEXT,
  STRINGDATA LONGTEXT,
  BINARYDATA LONGBLOB,
  LASTUPDATEDDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (USERID)
);

/***********************************************************  
MY_ASPNET_ROLES
***********************************************************/
CREATE TABLE MY_ASPNET_ROLES (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  APPLICATIONID INT(11) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

/***********************************************************  
MY_ASPNET_SCHEMAVERSION
***********************************************************/
CREATE TABLE MY_ASPNET_SCHEMAVERSION (
  VERSION INT(11) DEFAULT NULL
);

/***********************************************************  
MY_ASPNET_SESSIONCLEANUP
***********************************************************/
CREATE TABLE MY_ASPNET_SESSIONCLEANUP (
  LASTRUN DATETIME NOT NULL,
  INTERVALMINUTES INT(11) NOT NULL
);

/***********************************************************  
MY_ASPNET_SESSIONS
***********************************************************/
CREATE TABLE MY_ASPNET_SESSIONS (
  SESSIONID VARCHAR(255) NOT NULL,
  APPLICATIONID INT(11) NOT NULL,
  CREATED DATETIME NOT NULL,
  EXPIRES DATETIME NOT NULL,
  LOCKDATE DATETIME NOT NULL,
  LOCKID INT(11) NOT NULL,
  TIMEOUT INT(11) NOT NULL,
  LOCKED TINYINT(1) NOT NULL,
  SESSIONITEMS LONGBLOB,
  FLAGS INT(11) NOT NULL,
  PRIMARY KEY (SESSIONID,APPLICATIONID)
);

/***********************************************************  
MY_ASPNET_USERS
***********************************************************/
CREATE TABLE MY_ASPNET_USERS (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  APPLICATIONID INT(11) NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  ISANONYMOUS TINYINT(1) NOT NULL DEFAULT '1',
  LASTACTIVITYDATE DATETIME DEFAULT NULL,
  PRIMARY KEY (ID)
);

/***********************************************************  
MY_ASPNET_USERSINROLES
***********************************************************/
CREATE TABLE MY_ASPNET_USERSINROLES (
  USERID INT(11) NOT NULL DEFAULT '0',
  ROLEID INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (USERID,ROLEID)
);

/***********************************************************  
TABELA
***********************************************************/
CREATE TABLE TABELA (
  ID INT(11) NOT NULL,
  NOME VARCHAR(20) NOT NULL,
  DATA DATE NOT NULL,
  STATUS CHAR(1) NOT NULL,
  SALARIO DECIMAL(11,0) DEFAULT NULL
);

INSERT INTO MY_ASPNET_APPLICATIONS (ID, NAME, DESCRIPTION) VALUES 
  (1,'/','MYSQL PROFILE PROVIDER');
COMMIT;

INSERT INTO MY_ASPNET_PROFILES (USERID, VALUEINDEX, STRINGDATA, BINARYDATA, LASTUPDATEDDATE) VALUES 
  (1,'NOME/0/0/3:','AAA','','2011-01-24 20:54:10');
COMMIT;

INSERT INTO MY_ASPNET_SCHEMAVERSION (VERSION) VALUES 
  (6);
COMMIT;

INSERT INTO MY_ASPNET_SESSIONCLEANUP (LASTRUN, INTERVALMINUTES) VALUES 
  ('2011-01-24 20:52:30',10);
COMMIT;

INSERT INTO MY_ASPNET_USERS (ID, APPLICATIONID, NAME, ISANONYMOUS, LASTACTIVITYDATE) VALUES 
  (1,1,'CASA-PC\\JUNIOR',0,'2011-01-24 20:52:31');
COMMIT;
