DELETE FROM MY_ASPNET_SESSIONCLEANUP; 

ALTER TABLE MY_ASPNET_SESSIONCLEANUP ADD APPLICATIONID INT NOT NULL;
ALTER TABLE MY_ASPNET_SESSIONCLEANUP ADD PRIMARY KEY (APPLICATIONID);

UPDATE MY_ASPNET_SCHEMAVERSION SET VERSION=8;