 ALTER TABLE MYSQL_MEMBERSHIP 
            ADD PASSWORDKEY CHAR(32) AFTER PASSWORD, 
            ADD PASSWORDFORMAT TINYINT AFTER PASSWORDKEY, 
            CHANGE EMAIL EMAIL VARCHAR(128), COMMENT='2';
            