CREATE TABLE  MYSQL_MEMBERSHIP(PKID VARCHAR(36) NOT NULL,
              USERNAME VARCHAR(255) NOT NULL, 
              APPLICATIONNAME VARCHAR(255) NOT NULL,
              EMAIL VARCHAR(128) NOT NULL, 
              COMMENT VARCHAR(255) DEFAULT NULL,
              PASSWORD VARCHAR(128) NOT NULL, 
              PASSWORDQUESTION VARCHAR(255) DEFAULT NULL,
              PASSWORDANSWER VARCHAR(255) DEFAULT NULL, 
              ISAPPROVED TINYINT(1) DEFAULT NULL,
              LASTACTIVITYDATE DATETIME DEFAULT NULL, 
              LASTLOGINDATE DATETIME DEFAULT NULL,
              LASTPASSWORDCHANGEDDATE DATETIME DEFAULT NULL, 
              CREATIONDATE DATETIME DEFAULT NULL,
              ISONLINE TINYINT(1) DEFAULT NULL, 
              ISLOCKEDOUT TINYINT(1) DEFAULT NULL,
              LASTLOCKEDOUTDATE DATETIME DEFAULT NULL, 
              FAILEDPASSWORDATTEMPTCOUNT INT(10) UNSIGNED DEFAULT NULL,
              FAILEDPASSWORDATTEMPTWINDOWSTART DATETIME DEFAULT NULL,
              FAILEDPASSWORDANSWERATTEMPTCOUNT INT(10) UNSIGNED DEFAULT NULL,
              FAILEDPASSWORDANSWERATTEMPTWINDOWSTART DATETIME DEFAULT NULL,
              PRIMARY KEY  (PKID)) DEFAULT CHARSET=LATIN1 COMMENT='1';
              
CREATE TABLE  MYSQL_USERSINROLES(USERNAME VARCHAR(255) NOT NULL,
                ROLENAME VARCHAR(255) NOT NULL, APPLICATIONNAME VARCHAR(255) NOT NULL,
                KEY USERNAME (USERNAME,ROLENAME,APPLICATIONNAME)
                ) DEFAULT CHARSET=LATIN1 ROW_FORMAT=DYNAMIC;

CREATE TABLE MYSQL_ROLES(ROLENAME VARCHAR(255) NOT NULL,
                APPLICATIONNAME VARCHAR(255) NOT NULL, 
                KEY ROLENAME (ROLENAME,APPLICATIONNAME)
                ) DEFAULT CHARSET=LATIN1 ROW_FORMAT=DYNAMIC;
                
                