RENAME TABLE MY_ASPNET_APPLICATIONS TO MY_ASPNET_APPLICATIONS;
RENAME TABLE MY_ASPNET_MEMBERSHIP TO MY_ASPNET_MEMBERSHIP;
RENAME TABLE MY_ASPNET_PROFILES TO MY_ASPNET_PROFILES;
RENAME TABLE MY_ASPNET_ROLES TO MY_ASPNET_ROLES;
RENAME TABLE MY_ASPNET_SCHEMAVERSION TO MY_ASPNET_SCHEMAVERSION;
RENAME TABLE MY_ASPNET_SESSIONCLEANUP TO MY_ASPNET_SESSIONCLEANUP;
RENAME TABLE MY_ASPNET_SESSIONS TO MY_ASPNET_SESSIONS; 
RENAME TABLE MY_ASPNET_USERS TO MY_ASPNET_USERS;
RENAME TABLE MY_ASPNET_USERSINROLES TO MY_ASPNET_USERSINROLES;

UPDATE MY_ASPNET_SCHEMAVERSION SET VERSION=7;