CREATE TABLE MY_ASPNET_SESSIONS
(
  SESSIONID       VARCHAR(191)  NOT NULL,
  APPLICATIONID   INT       NOT NULL,
  CREATED         DATETIME  NOT NULL,
  EXPIRES         DATETIME  NOT NULL,
  LOCKDATE        DATETIME  NOT NULL,
  LOCKID          INT       NOT NULL,
  TIMEOUT         INT       NOT NULL,
  LOCKED          TINYINT(1)   NOT NULL,
  SESSIONITEMS    BLOB,
  FLAGS           INT   NOT NULL,
  PRIMARY KEY (SESSIONID,APPLICATIONID)
)  DEFAULT CHARSET=LATIN1;

/*
  CLEANING UP TIMED OUT SESSIONS.
  IN 5.1 EVENTS PROVIDE A SUPPORT FOR PERIODIC JOBS.
  IN OLDER VERSION WE NEED A DO-IT-YOURSELF EVENT.
*/
CREATE TABLE MY_ASPNET_SESSIONCLEANUP
(
  LASTRUN   DATETIME NOT NULL,
  INTERVALMINUTES INT NOT NULL
);

INSERT INTO MY_ASPNET_SESSIONCLEANUP(LASTRUN,INTERVALMINUTES) VALUES(NOW(), 10);

UPDATE MY_ASPNET_SCHEMAVERSION SET VERSION=5;

