ALTER TABLE MY_ASPNET_MEMBERSHIP CONVERT TO CHARACTER SET DEFAULT;
ALTER TABLE MY_ASPNET_ROLES CONVERT TO CHARACTER SET DEFAULT;
ALTER TABLE MY_ASPNET_USERSINROLES CONVERT TO CHARACTER SET DEFAULT;

UPDATE MY_ASPNET_SCHEMAVERSION SET VERSION=4 WHERE VERSION=3;
